### ISSUE TITLE
Is there a way to output raw PPG data from this device?

### ISSUE THREAD

**Issue by FigsnApples** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#29]
I know one can use the MAX30101 to get raw PPG data but I'm wondering if there is to enable the Max30101 library onto this board to get raw PPG values? 

Please let me know. 

Thanks!

**Comment by edspark** [comment]
The function of the MAX32664 on this design is to utilize the raw data from the MAX30101 to calculate various bio-metric data and because of that, the data lines from the MAX30101 are connected directly to the MAX32664 and are not broken out for the user. Unfortunately you won't be able to use our other library.
